spring.application.name=notification-service
server.port=${PORT:8085}
server.address=0.0.0.0

# DB independiente para Telegram Users (chat_ids)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:db_notification_service}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${MYSQLUSER:root}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${MYSQLPASSWORD:}}
spring.jpa.hibernate.ddl-auto=update

# Configuracion SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SMTP_USERNAME:certimentor@gmail.com}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

brevo.api.key=${BREVO_API_KEY:}


mailjet.api.key=${MAILJET_API_KEY:}
mailjet.secret.key=${MAILJET_SECRET_KEY:}

telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
internal.service.token=${INTERNAL_SERVICE_TOKEN:}
