spring.application.name=user-service-g4

# Configuración del puerto del servidor
server.port=8081

# Configuración de la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_mentorias_g4?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password= #<-- PON TU CONTRASEÑA DE MYSQL AQUÍ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
